### ISSUE TITLE
can you teach me how can i add the lora module in the ns3

### ISSUE THREAD

**Issue by nurdila88** [signetlabdei/lorawan#111]
## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - ns-3 version:
  - lorawan module version:
  - Platform:
  - Compiler:

**Comment by nurdila88** [comment]
i really appreaciate if you can give me some learning..

**Comment by DvdMgr** [comment]
Instructions on how to install the module are available in the project readme!
