### ISSUE TITLE
lowDataRateOptimizationEnabled set to 0 in class-a-end-device-lorawan-mac

### ISSUE THREAD

**Issue by brunocitoni** [signetlabdei/lorawan#113]
## Expected Behavior
lowDataRateOptimization should be set to 0 or 1 depending on symbol time Tsym = 2^SF/BW. This should be set to 1 when Tsym is greater than 16ms, which in the case of a 125k BW is for SF 11 and 12. This gives rise to slightly different ToA than expected for packets using these spreading factors.

ref.
[(p.31)](https://www.mouser.co.uk/pdfdocs/sx1276_77_78_79.pdf )
[(p.8)](https://www.rs-online.com/designspark/rel-assets/ds-assets/uploads/knowledge-items/application-notes-for-the-internet-of-things/LoRa%20Design%20Guide.pdf)

## Actual Behavior
lowDataRateOptimization is always set to 0

**Comment by DvdMgr** [comment]
Should be fixed in f20251f928d64d74ab4294c9a8fb64ba83a56dbc, so I'm closing for now. Feel free to reopen this issue if anything looks strange to you!
