### ISSUE TITLE
End Device-Side ADR

### ISSUE THREAD

**Issue by brunocitoni** [signetlabdei/lorawan#117]
Looking at the source code and the documentation provided it seems that ADR is currently only available at the Network end. 

I am looking into implementing the End Device side of it as well, but thought I would double check whether this is already being done?

**Comment by renzoe** [comment]
Hi! Yes, it is already implemented the ED ADR (The "ADR backoff" the only one from the standards).
Check here:
https://github.com/signetlabdei/lorawan/blob/develop/model/class-a-end-device-lorawan-mac.cc#L84

Regards!

**Comment by brunocitoni** [comment]
Perfect, thanks!
