### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by SaM885** [signetlabdei/lorawan#118]
## Actual Behavior
Build failed
 -> task in 'ns3-aqua-sim-ng' failed with exit status 1 (run with -v to display more information)
 -> task in 'ns3-aqua-sim-ng' failed with exit status 1 (run with -v to display more information)

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - ns-3 version:3.34
  - lorawan module version:ns3-allinone-3.34
  - Platform:ubuntu
  - Compiler:

**Comment by DvdMgr** [comment]
This is not enough information to help in any way. Please open another issue and fill the template appropriately, with detailed steps to reproduce the problem. Closing.
