### ISSUE TITLE
bash: ./waf: No such file or directory

### ISSUE THREAD

**Issue by Junaid-Q** [signetlabdei/lorawan#129]
Hi, 

I am compiling this repository, however, it gives me the following error given below. Can someone please help me out?
bash: ./waf: No such file or directory

![image](https://user-images.githubusercontent.com/12583457/201539582-d1bc6cc6-14dc-4745-b019-9bcf42464c2b.png)

**Comment by sanjay-charran** [comment]
The "waf" script was replaced by the "ns3" one in the newer versions of ns3 I believe. This command ought to work for configuring for your version:
`./ns3 configure --enable-tests --enable-examples`

However, this module was designed for ns3.29 according to the "NS3-VERSION" file in the repository and I'm not certain if it'll work, so I would recommend you try to install ns3.29 if compiling the repository on the version you're running fails.

**Comment by Junaid-Q** [comment]
@sanjay-charran Thank you so much, you are right. I then tried with `./ns3 configure --enable-tests --enable-examples` and compiled successfully. 
Thanks again

**Comment by usamamustafa36** [comment]
I have replaced the waf script with ns3. it worked. however, when you run the test, it doesnt work and this error is shown. Can someone help ?
![Screenshot from 2023-09-01 09-30-20](https://github.com/signetlabdei/lorawan/assets/128321094/1cfda8be-89d7-490e-8c2c-1ffe35941de2)

**Comment by usamamustafa36** [comment]
The test was passed but when i run the example this error comes.. i am using ./ns3 instead of waf script
![Screenshot from 2023-09-01 10-17-32](https://github.com/signetlabdei/lorawan/assets/128321094/f9980f96-f0a1-4110-ae82-1a8bba6e3375)

**Comment by sanjay-charran** [comment]
@usamamustafa36 I believe it should be `./ns3 run [example-name]`

https://www.nsnam.org/docs/tutorial/html/quick-start.html

**Comment by pagmatt** [comment]
Updated the README to reflect the build system changes.
