### ISSUE TITLE
NS3 ERROR: LoRaMacHeader was not declared in this scope

### ISSUE THREAD

**Issue by SonileKM** [signetlabdei/lorawan#177]
## Expected Behavior
Expected to transmit, receive packet and save that it has been received without getting the above error when we used the following code to indicate and save that the message is transmitted and received.

// Save that the message has been transmitted
void
Transmitted (const Ptr<const Packet> packet)
{
	if (Simulator::Now().GetSeconds() > measurementStart)
	{
		Ptr<Packet> copy = packet->Copy();
		LoRaMacHeader header;
		copy->RemoveHeader(header);
		Address addr = (header.GetAddr());
                std::get<0>(errorMap[addr])++;
        }
}

// save that a message has been received
	void
Received (const Ptr<const Packet> packet)
{
	if (Simulator::Now().GetSeconds() > measurementStart)
	{
	Ptr<Packet> copy = packet->Copy();
	LoRaMacHeader header;
	copy->RemoveHeader(header);
	GwTrailer trailer;
	copy->RemoveTrailer (trailer);
	Address addr = (header.GetAddr());
	std::get<1>(errorMap[addr])++;
	if ( trailer.GetGateway () == GetClosestGateway (deviceMap[addr]->GetNode ()->GetObject<MobilityModel>())) 
		std::get<3>(errorMap[addr])++;
	}
}

// save that a message has been uniquely received
	void
ReceivedUnique (const Ptr<const Packet> packet)
{
	if (Simulator::Now().GetSeconds() > measurementStart)
	{
		Ptr<Packet> copy = packet->Copy();
		LoRaMacHeader header;
		copy->RemoveHeader(header);
		Address addr = (header.GetAddr());
		std::get<2>(errorMap[addr])++;
	}
}

## Actual Behavior
For the code " LoRaMacHeader header;  "  and " copy->RemoveHeader(header); "
, We are getting the following errors:
1. In function ‘void Transmitted(ns3::Ptr<const ns3::Packet>)’:error: ‘LoRaMacHeader’ was not declared in this scope.
2. ‘header’ was not declared in this scope

## Steps to Reproduce the Problem

  1. I found  issue number 40 and the suggestion and code that was given.
  2. I tried to change LoRaMacHeader to LoraMacHeader and also bring it before ptr<packet> copy =packet->Copy(); to align with the code in ssue 40 but the error was still coming.
 

## Specifications

  - ns-3 version: ns-3.41
  - lorawan module version: ns-3-dev
  - Platform: Ubuntu 20.04
  - Compiler: gcc

**Comment by nondetalle** [comment]
Neither `LoRaMacHeader` nor `LoraMacHeader` are classes of this module. Did you mean [`LorawanMacHeader`](https://signetlabdei.github.io/lorawan/html/db/d7e/classns3_1_1lorawan_1_1_lorawan_mac_header.html)?

**Comment by SonileKM** [comment]
Thanks Alessandro. I must have been using classes outside this module. I
will align to what is applicable to this module.

**Comment by nondetalle** [comment]
Recently we restored the [online API documentation](https://signetlabdei.github.io/lorawan/html/d5/d00/group__lorawan.html). As a suggestion for the future, check the API documentation for class names giving you errors.
