### ISSUE TITLE
Changing SF in EndDevice

### ISSUE THREAD

**Issue by JuanUrena** [signetlabdei/lorawan#182]
## Expected Behavior
According with the ADR component (around line 215)     
    _// If, on the other hand, the number of steps is negative (margin_SNR is
    // negative, so its decimal value is low) increase the transmission power
    //(note that the spreading factor is not incremented as this particular algorithm
    // expects the node itself to raise its spreading factor whenever necessary)._

## Actual Behavior
I have been playing around, and even if the node is not able to comunicate with the GW, he never increase the SF. So it is a little bit unclear to me the expected behaviour here. Is the ED just changing the SF to avoid collisions? Or is something not working. Under mz understanding, the ASR should be able to also select the SF, no?

## Steps to Reproduce the Problem

  1. I adjust the ADR to comunicate the node to use SF = 5 and Tx = 2, and then I blocked any new update from the ADR. So basically the ED is not able to achive the GW as the SNR is not enough.

## Specifications

  - ns-3 version: 43
  - lorawan module version: 0.3.1
  - Platform: Ubuntu 24.04
  - Compiler: gcc version 13.2.0

**Comment by nondetalle** [comment]
Hi, there is an attribute of the `EndDeviceLorawanMac` class called `EnableEDDataRateAdaptation` that must be set to true to enable SF adaptation on the device's side. See the examples on how to chage ns-3 attributes globally. Mind that the current implementation is old (LoRaWAN specs v1.0.2, see #171) and we are planning to bring it up to date in the near future. Let me know if that fixed it for you.

**Comment by JuanUrena** [comment]
Hi, yes, thanks. You gave me the right place to look at. Now it works as I was expecting.

Thank you very much!
