### ISSUE TITLE
Is there a way to make a .pcap file?

### ISSUE THREAD

**Issue by thummim** [signetlabdei/lorawan#27]
## Expected Behavior

want to make a .pcap file

## Actual Behavior

I know that ns-3 supports to make .pcap file and I just don't know where to put 
pointToPoint.EnablePcapAll (“filename”); 
this code.

## Specifications

* ns-3 version: 3.29
* lorawan module version: 0.2.0
* Platform: Kali linux
* Compiler: cc 10.0.0

**Comment by DvdMgr** [comment]
Hi, .pcap files are not currently supported!

**Comment by thummim** [comment]
thanks for the answer 👍 :)
