### ISSUE TITLE
Setting different data rate for different set of end device

### ISSUE THREAD

**Issue by shobhuagg1992** [signetlabdei/lorawan#41]
I am trying to configure different end devices with different values of spreading factors but it seems like SF can be configured using datarate. I am quite new with NS-3
Can you give a simple illustration of how to use the SetDataRate method for it?

Thanks

**Comment by DvdMgr** [comment]
Hi, in the EU868 region, there's a direct correspondence between Data Rate and Spreading Factor: DR0 = SF12BW125, DR1 = SF11BW125, ..., DR5 = SF7BW125. 

You can find more about this correspondence on the Regional Parameters document of the LoRaWAN standard!

**Comment by shobhuagg1992** [comment]
Thanks for your response. I made some modifications in the helpers and I am able to set different spreading factors for a group of end devices.

**Comment by EduLima7** [comment]
In the EU868, you can do it using `LoraMacHelper::SetSpreadingFactorsUp` method. This method sets the Data Rate from the sensitivity of each End Device. For example, on `complete-network-example` line `macHelper.SetSpreadingFactorsUp (endDevices, gateways, channel);` sets Data Rate of `EndDevices` NodeContainer.

**Comment by shobhuagg1992** [comment]
Thanks. I was able to configure different SF for different nodes.
