### ISSUE TITLE
Capturing Downlink packets

### ISSUE THREAD

**Issue by kaustubhshrotri** [signetlabdei/lorawan#45]
Hello All,

I want to capture  downlink packets during a simulation.
Is there a way to do so?

I am using Complete-network-example.cc for my simulation with modifications.

Thanks

**Comment by DvdMgr** [comment]
This sounds similar to #40 - can you elaborate on what you need, more precisely? Maybe we can coordinate with @Fundoprajakta to make it happen.

**Comment by kaustubhshrotri** [comment]
Hello,

My issue is to detect in which receive window the downlink packets are received.
is there a way?

**Comment by DvdMgr** [comment]
As of now, we do not save this information. However, you can easily customize the `LoraPacketTag` class to memorize the number of the receive window that was used in the reception of the ACK, modify the packet's tag upon reception and retrieve the information later, for instance from within the `LoraPacketTracker`
