### ISSUE TITLE
Tests, tests, tests!

### ISSUE THREAD

**Issue by DvdMgr** [signetlabdei/lorawan#49]
Tests are a vital component of the module, and a great way to get started if you want to understand what's going on under the hood. 

As of now, we have tests for the PHY layer model implementation, but more is needed for the MAC layer and for Network Server functionality.

If you want to contribute towards this, you are welcome! Please feel free to use this issue to ask questions on how to get started - I will be happy to assist you.

**Comment by bolasoma** [comment]
Hello David,

I would like to know if it is possible to add a LDAP authentication to this module, any guidance on how to get started will be very welcome.

Cheers,

Soma

**Comment by gaurivn** [comment]
@DvdMgr, I would like to work on this issue. Could you please advise me on the same

**Comment by DvdMgr** [comment]
Sure! A good starting point would be to make sure tests run correctly, both on the master and on the develop branches. If this is not the case, we need to identify the test that does fails and understand why. You can follow the readme instructions to compile the module and run the tests!

**Comment by gaurivn** [comment]
Thank you Sir for replying. I will do accordingly.

**Comment by gaurivn** [comment]
> Sure! A good starting point would be to make sure tests run correctly, both on the master and on the develop branches. If this is not the case, we need to identify the test that does fails and understand why. You can follow the readme instructions to compile the module and run the tests!

The lorawan test suite passed on the develop branch with no errors, but on master branch, it gave errors for lorawan/model/building-penetration-loss.cc, please find the screenshot attached below:
![lorawan_test-develop](https://user-images.githubusercontent.com/48416306/111326438-8cc4ff80-8692-11eb-84af-7196daa89d84.png)

**Comment by DvdMgr** [comment]
Ok, as I expected, it's failing due to a change in the ns-3 APIs - the IsOutdoor method was deprecated, !IsIndoor() should be used instead. Can you fix it? I'll be happy to merge your pull request!

**Comment by gaurivn** [comment]
> Ok, as I expected, it's failing due to a change in the ns-3 APIs - the IsOutdoor method was deprecated, !IsIndoor() should be used instead. Can you fix it? I'll be happy to merge your pull request!

I used !IsIndoor() instead but I am still getting more errors, I will try fix those..please find the screenshots attached below:
![Screenshot from 2021-03-17 16-38-56](https://user-images.githubusercontent.com/48416306/111462351-59db4400-8744-11eb-833d-a22d474ff233.png)
![Screenshot from 2021-03-17 16-39-02](https://user-images.githubusercontent.com/48416306/111462374-5fd12500-8744-11eb-8ca0-7a3117f64794.png)

**Comment by DvdMgr** [comment]
It looks like the problem is that in the tests we are trying to compare an instance of ns3::Time with an integer. This is happening inside the NS_TEST_EXPECT_MSG_EQ macro - it should be enough to change that 0 to a Seconds(0), so that it becomes a Time instance!

**Comment by gaurivn** [comment]
Thank you, I made the change and the one error remaining was due to deprecated method - MakeMobilityModelConsistent() in complete-network-example.cc
![Screenshot from 2021-03-18 18-24-20](https://user-images.githubusercontent.com/48416306/111629708-97f56800-8817-11eb-8ce6-8f24ba38b6ea.png)
I commented it out and committed again and the lorawan test suite passed without errors.
![Screenshot from 2021-03-18 18-34-27](https://user-images.githubusercontent.com/48416306/111630797-bc9e0f80-8818-11eb-90f9-20e2fbc0414b.png)
