### ISSUE TITLE
Different packet intervals when Using PeriodicSender  class

### ISSUE THREAD

**Issue by Prapi123** [signetlabdei/lorawan#55]
Hello,

First I wonder, Is there a way I can change the packet interval during simulation. for Example first 2 packets are sent at an packet  interval of 10 min and then rest of then after rest with much  larger interval time.

**Comment by DvdMgr** [comment]
I think you are better off writing your own version of PeriodicSender if you want this behavior!

**Comment by Prapi123** [comment]
You can close this issue. This issue is resolved
