### ISSUE TITLE
Update module documentation

### ISSUE THREAD

**Issue by DvdMgr** [signetlabdei/lorawan#58]
As of now, we have a `lorawan.rst` file that describes some of the functionalities of the module, but this is not enough. I've identified the following tasks to improve the documentation of the module: 
- Add a compiled documentation page, possibly hosted through Github Pages for immediate access by users.
- Add documentation on how the Network Server works
- Add description of tests, underlying models and validation
- Add a page describing how the simulator was validated by comparison with a mathematical model

**Comment by KishkinJ10** [comment]
hello everyone , i am a beginner and i want to work on this issue can someone tell me how should i start .

**Comment by DvdMgr** [comment]
Hi! A pre-requisite to start working on this issue is a somewhat deep knowledge of both the LoRa modulation and the LoRaWAN protocol, in addition to an understanding of how these components are modeled in ns-3. If you have these attributes, feel free to start tackling one of the listed bullet points.

**Comment by wilsongus2003** [comment]
Good afternoon, where can I get information on how to generate pcap files, oh how to track package traces?
