### ISSUE TITLE
I need to analyze the security features of LPWAN technologies.

### ISSUE THREAD

**Issue by OniremE** [signetlabdei/lorawan#60]
Is it possible use this module to analyze the security parameters of LPWAN technologies?

**Comment by DvdMgr** [comment]
Currently, we don't model any of the security features - what exactly are
you looking to simulate?

**Comment by OniremE** [comment]
I want to analyze the encryption feature and find the possible vulnerabilities in LoraWan and Sigfox.

**Comment by DvdMgr** [comment]
In this case, I don't think this is the right tool: since we focus on analyzing the scalability of the network, we completely avoid modeling encryption to save computation time!

**Comment by OniremE** [comment]
could you give me a suggestion for me?

**Comment by DvdMgr** [comment]
I'm sorry, I don't have any experience with the security side of things in LoRaWAN - Google Scholar might be a good starting point!
