### ISSUE TITLE
ACK bit set wrongly at EndDeviceLorawanMac?

### ISSUE THREAD

**Issue by theelbowclaps** [signetlabdei/lorawan#67]
## Expected Behavior
In void EndDeviceLorawanMac::ApplyNecessaryOptions (LoraFrameHeader& frameHeader),
the frameHeader ACK bit should only be set if the end device has just received a confirmed downlink message.

## Actual Behavior
The ack bit is set based on Uplink message type. Ack = 1 if mType = CONFIRMED_DATA_UP.

## Steps to Reproduce the Problem
N/A

## Specifications
N/A

**Comment by DvdMgr** [comment]
You are right, this is wrong. Removed the check + setting of the ACK bit in 80eb5243bb3ee77eeaa409531fa90aaae9965941, since we don't support ACKs sent by EDs yet.

Thanks for pointing this out!
