### ISSUE TITLE
Downlink Transmission and Receive Power

### ISSUE THREAD

**Issue by Fundoprajakta** [signetlabdei/lorawan#70]
Hello,

How can I approach to find out Downlink Transmission power and Received  Power for signal?

Thanks and Regards

**Comment by DvdMgr** [comment]
Hi, are you looking for this information inside the `PacketTracker`?

**Comment by Fundoprajakta** [comment]
Hello,

My Idea is to get SNR and RSSI value for downlink as well.

**Comment by shobhuagg1992** [comment]
Hello Prajakta
Can you please let me know how to unable downlink traffic?

Thanks

**Comment by Fundoprajakta** [comment]
Hello @shobhuagg1992 

The Downlink traffic is already enabled in the module. You have to set LoraMacheader value to confirmed_data _up. 
With Packettracker you can compute the metrics.  You can check issue no. 40 which is closed now. I have discussed with @DvdMgr  about this earlier. You can also visit my profile and check lorawan repository which I forked from here to draw some inspiration from the changes that I have made.

Thanks

**Comment by shobhuagg1992** [comment]
Awesome. Thank you so much, will try that.
