### ISSUE TITLE
Out of GetBestGatewayForDevice() does not match to address of Gateway nodecontainer

### ISSUE THREAD

**Issue by Fundoprajakta** [signetlabdei/lorawan#74]
Hello,
I have extracted device gateway address using this below code
`for (NodeContainer::Iterator j = gateways.Begin ();
       j != gateways.End (); ++j)
  {
    Ptr<Node> node = *j;
    //uint32_t senderID = node->GetId ();
    //std::cout << "senderID: " << senderID << std::endl;
    Ptr<NetDevice> NetDevice = node->GetDevice(0);
    Address addr = NetDevice->GetAddress();
    std::cout << addr << std::endl;
  }`

And used NetworkStatus::GetBestGatewayForDevice()  method to get Gateway address. 

Both of them produce different output: 

![image](https://user-images.githubusercontent.com/37836476/74111727-e0763700-4bbc-11ea-8f41-4bd0bcd58d34.png)

Please suggest where I am going wrong. The basic idea is to get the Ptr(Node) corresponding to NetworkStatus::GetBestGatewayForDevice().

I tried extracting the Ptr(Node) from output of NetworkStatus::GetBestGatewayForDevice().
but the Node ID of gateway in Nodecontainer and the Node ID of GetBestGatewayForDevice() is different.

![image](https://user-images.githubusercontent.com/37836476/74112632-503bf000-4bc4-11ea-8d58-7cf8927e45de.png)

I am confused about this. 
I am using Network-server-example here.

Thanks

**Comment by DvdMgr** [comment]
The address returned by `GetBestGatewayForDevice` is the address of the `PointToPointNetDevice` connecting the GW to the NS, so it is expected you will get different results. If you want to get a `Ptr` to the best GW, you should be able to get them from within the `NetworkStatus` object: this object holds a map linking the addresses returned by `GetBestGatewayForDevice` to a `GatewayStatus` object, which in turn contains a pointer to the GW's Mac. You can see this is used in `src/lorawan/model/network-status.cc`, line 157!

**Comment by DvdMgr** [comment]
Fixed in #76
