### ISSUE TITLE
LorawanMacHelper::ConfigureForAlohaRegion for a gateway node seems like it's not doing the right thing

### ISSUE THREAD

**Issue by gdelazzari** [signetlabdei/lorawan#75]
While inspecting the code I noticed what I think it's a weird thing. The method
```c++
void LorawanMacHelper::ConfigureForAlohaRegion (Ptr<GatewayLorawanMac> gwMac) { ... }
```
is calling `ApplyCommonEuConfigurations (gwMac)`. Shouldn't it be calling `ApplyCommonAlohaConfigurations (gwMac)` instead? Or is there a particular reason why it's not as I expected?

Here is relevant line of code
https://github.com/signetlabdei/lorawan/blob/80eb5243bb3ee77eeaa409531fa90aaae9965941/helper/lorawan-mac-helper.cc#L182

I don't think it matters as far as the simulation behaviour goes, since the only difference I can spot is that `ApplyCommonEuConfigurations` registers all the 3 channels in the `LogicalLoraChannelHelper`, but in `ConfigureForAlohaRegion (Ptr<GatewayLorawanMac> gwMac)` they're not used and only one receive path is allocated on the frequency 868.1 in any case.

Feels like a copy-pasted line that was forgot to change, but I might be totally wrong!

**Comment by DvdMgr** [comment]
Yes, this looks like a copy+paste error that, as you said, has no real consequence on behavior. Want to submit a pull request fixing this?
