### ISSUE TITLE
How to modify to support multicast？

### ISSUE THREAD

**Issue by QiuYukang** [signetlabdei/lorawan#82]
I have made some modifications so that the Network Server can send packet to EndDevice at any time. I want to implement the multicast function, can you give me some guidance about this? Thank you very much!

**Comment by DvdMgr** [comment]
Hi!
In order to implement Multicast, I'd say the very first thing is to implement Class B or Class C devices, since a subset of Class A devices will need to switch to that behavior for a set amount of time. I'd keep development of `NetworkServer` code as the last part!
