### ISSUE TITLE
Incomplete comment for vector packetCounts

### ISSUE THREAD

**Issue by JacoTuks** [signetlabdei/lorawan#85]
Hi,

I hope I'm correct here (my first attempting at making an issue).

## Expected Behavior
All 6 fields of the vector packetCounts defined in lora-packet-tracker.cc

## Actual Behavior
The description for the contents of packetCounts in lines 224-226 and 286-288 of lora-packet-tracker.cc is missing a field. The one for "LOST_BECAUSE_TX".

packetCounts's 0 - 4 are defined, but packetCount's 5 is not.

## Steps to Reproduce the Problem

  1. Inspect lora-packet-tracker.cc [line 224 ](https://github.com/signetlabdei/lorawan/blob/develop/helper/lora-packet-tracker.cc#L224)
  2. Inspect lora-packet-tracker.cc [line 286 ](https://github.com/signetlabdei/lorawan/blob/develop/helper/lora-packet-tracker.cc#L286)
 
## Specifications
  - lorawan module version: c48046c

**Comment by DvdMgr** [comment]
Correct, thanks for pointing this out! If you want to create a pull request fixing this, feel free to do so! Otherwise, I can take care of this.
