### ISSUE TITLE
Run simulation on multiple cores

### ISSUE THREAD

**Issue by Fundoprajakta** [signetlabdei/lorawan#86]
Hello,

I have option to use multiple cores on a server to run the LoRa ns3 simulator.
Is there a way , I can run the simulation on multiple cores?

Thanks and Regards

**Comment by JacoTuks** [comment]
Hi,

Have a look at https://github.com/signetlabdei/sem

That will do the job!

**Comment by DvdMgr** [comment]
Closing, as @JacoTuks replied just as I would have.
