### ISSUE TITLE
¿how to add pcap helpers?

### ISSUE THREAD

**Issue by OniremE** [signetlabdei/lorawan#87]
Hello, I am restarting the research. I want to add pcap helpers ... can you help me to do it?

**Comment by DvdMgr** [comment]
Hi!
Sure - I think looking at the ns-3 documentation could be a good starting point. As an entry point, we can add an EnablePcap method to LoraHelper. I'm not sure how pcap tracing works - can you find some references in the ns-3 manual?

Also, how would you visualize these .pcap files? Does wireshark support LoRaWAN packets?

**Comment by DvdMgr** [comment]
Closing, relevant pull request linked above.
