### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by ddujovne** [signetlabdei/lorawan#88]
## Expected Behavior

The documentation link should work

## Actual Behavior

The file Readme.md has a broken link:

[API documentation](https://signetlabdei.github.io/lorawan/html/index.html).

[Module Documentation](https://signetlabdei.github.io/lorawan/models/build/html/lorawan.html).

## Steps to Reproduce the Problem

  1. Click on both broken links.

## Specifications

Not needed.
  - ns-3 version:
  - lorawan module version:
  - Platform:
  - Compiler:

**Comment by DvdMgr** [comment]
Should be fixed in acc083d00277698ad7bfcfa829e716dc9b0fe70c - thanks for pointing this out!

New links are https://signetlabdei.github.io/lorawan-docs/html/index.html and https://signetlabdei.github.io/lorawan-docs/html/index.html
