### ISSUE TITLE
Iteration bug in funcntion LoraInterferenceHelper::CleanOldEvents 

### ISSUE THREAD

**Issue by taramaorisky** [signetlabdei/lorawan#93]
## Expected Behavior
clean up all old events.

## Actual Behavior
it would skip some old event because of wrong iterator step.

## Steps to Reproduce the Problem
1. if i would like to erase odd numbers in vector<int> nums, this code would skip some odd numbers:
![Snipaste_2020-09-22_11-35-19](https://user-images.githubusercontent.com/13379068/93841928-b561d300-fcc7-11ea-84b4-4bbe040caced.jpg)
  it prints like this:
![Snipaste_2020-09-22_11-36-18](https://user-images.githubusercontent.com/13379068/93841977-daeedc80-fcc7-11ea-8bed-b9cd7e38e554.jpg)

2. add an **_else_** would fix it:
![Snipaste_2020-09-22_11-36-18](https://user-images.githubusercontent.com/13379068/93842050-2608ef80-fcc8-11ea-8deb-4c987e6fafd7.jpg)

3. so the same trivial bug exists in funcntion LoraInterferenceHelper::CleanOldEvents:
![Snipaste_2020-09-22_11-40-42](https://user-images.githubusercontent.com/13379068/93842145-76804d00-fcc8-11ea-8c64-8a9a3d586420.jpg)

## Specifications

  - ns-3 version: ns-3.31
  - lorawan module version: 0.3.1
  - Platform: Ubuntu 18.04.5 LTS
  - Compiler: gcc 7.5.0

**Comment by DvdMgr** [comment]
Thanks for pointing this out! Fixed in d0349ca8617e03ce35cbef33e9e89fbf796d8a10.
