### ISSUE TITLE
Can this be used with only LoRa physical layer

### ISSUE THREAD

**Issue by fmc5046** [signetlabdei/lorawan#97]
Hi I was curious if there is a way to run this without the LoRaWAN layer and only use the LoRa physical layer?

**Comment by DvdMgr** [comment]
There should be a way, and if there isn't, then it's a bug :)

If you look at the examples, we typically use a LorawanHelper that encapsulates a LorawanMacHelper and a LoraPhyHelper - I suggest you look into what these classes do to understand how the various layers are configured. You should be able to only employ the LoraPhyHelper to set up your devices to only have the PHY layer, but I don't think we have tested this in a while, so things might break. Let us know in this issue if they do!
