### ISSUE TITLE
ALOHA matrix in LoraInterferenceHelper

### ISSUE THREAD

**Issue by brunocitoni** [signetlabdei/lorawan#98]
## Expected Behavior
As far as I understand, using the ALOHA Matrix in LoraInterferenceHelper should give rise to no collision between packets sent on different SFs

## Actual Behavior
Packets of different SF can still collide and be lost using minf as the threshold, as the resulting SNIR could be a negative dB value but minf is always positive. Using -inf instead seems to fix this.

## Steps to Reproduce the Problem

  1. Set up 6 nodes with different SF and use one shot sender to send 6 packets at the same time
  2. Observe debug info from LoraInterferenceHelper

**Comment by DvdMgr** [comment]
You are right! Setting the threshold as -inf fixes the issue. Fixed in 2340df1
